### ISSUE TITLE
Problem installing wheel on Ubuntu:focal

### ISSUE THREAD

**Issue by andyfaff** [isuruf/ocl-wheels#2]
I'm trying to use pyopencl on Ubuntu:focal for some CI testing. With a little trying I managed to install [`pocl`](https://github.com/pocl/pocl) from source.

I then try to `python3.8 -m pip install pyopencl[pocl]` which tries to install `pocl-binary-distribution`. The fact that binary distribution is in the package name leads me to think that perhaps the original pocl build wasn't necessary. Anyway, when I try to to that I get the following error:

```
python3.8 -m pip install pocl_binary_distribution
Collecting pocl_binary_distribution
  Using cached https://files.pythonhosted.org/packages/92/e2/de2b1d2b0c95634f517ce2ba27d8f00aa948b40f05b330b2d990216d9e3d/pocl_binary_distribution-1.3.post1-py2.py3-none-manylinux1_x86_64.whl
Installing collected packages: pocl-binary-distribution
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 356, in run
    requirement_set.install(
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 780, in install
    requirement.install(
  File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 1057, in move_wheel_files
    move_wheel_files(
  File "/usr/lib/python3/dist-packages/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/usr/lib/python3/dist-packages/pip/wheel.py", line 323, in clobber
    shutil.copyfile(srcfile, destfile)
  File "/usr/lib/python3.8/shutil.py", line 259, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
NotADirectoryError: [Errno 20] Not a directory: '/usr/local/lib/python3.8/dist-packages/pyopencl/.libs/libpocl-3a06e60a.so'
```

**Comment by isuruf** [comment]
Sorry, didn't see this issue. The problem is that this package requires that `pyopencl` be installed using pip as well and I don't see any way to get around that issue.

**Comment by drewbo** [comment]
@andyfaff I think this is also caused by https://github.com/inducer/pyopencl/issues/438 and should be resolved by https://github.com/inducer/pyopencl/pull/439
